```{r}
library(dplyr)
library(ggplot2)
library(ggtree)
library(viridis)
library(phytools)
library(ggnewscale)
library(ggtreeExtra)
```

```{r}

# Read the tree file
tree <- read.tree("modified.tree.txt")

# Check the structure of straintree
# Root the tree
tree <- root(tree, outgroup = "Paraglomus_occultum")

to_drop <- c("Mortierella_globalpina", "Archaeospora_ecuadoriana","Acaulospora_entreriana","Acaulospora_laevis","Acaulospora_spinosa","Acaulospora_cavernata","Acaulospora_colombiana", "Paraglomus_occultum")

tree <- drop.tip(tree, to_drop)

```

```{r}
# Drop the specified tips
#straintree <- drop.tip(rooted_tree, "Chaetosphaeria_ciliata")
```



# Based on the structure of straintree, identify the correct attribute for bootstrap values
```{r}

p1 <- ggtree(tree, layout="rectangular", size=.75, aes(color=as.numeric(label))) +
  scale_color_gradient("Bootstrap", low = "green", high = "black", limits=c(0,100)) + 
  new_scale_color() +
  geom_tiplab(aes(color=ifelse(grepl("ASV", label), "blue", "black")), size=2.75) + 
  theme(legend.position = "bottom") +
  scale_y_continuous(limits=c(1, 225)) +
  scale_color_identity()


plot(p1)
```

```{r}

# Save the plot to an image file
ggsave("NCBIreftree.png", p1, width = 25, height = 25)
```


```{r}
# save the plot to an svg file
svg("./NCBIreftree.svg", width = 25, height = 25)
p1
dev.off()
```
