```{r}
library(dplyr)
library(ggplot2)
library(ggtree)
library(viridis)
library(phytools)
library(ggnewscale)
library(ggtreeExtra)
```

```{r}

# Read the tree file
tree <- read.tree("ITOL.treefile")

# Check the structure of straintree
# Root the tree
tree <- root(tree, outgroup = "Mortierella_globalpina")

tree <- drop.tip(tree, "Mortierella_globalpina")

```

```{r}
# Drop the specified tips
#straintree <- drop.tip(rooted_tree, "Chaetosphaeria_ciliata")
```



# Based on the structure of straintree, identify the correct attribute for bootstrap values
```{r}
# Modify the tree labels to exclude anything after the decimal
tree$tip.label <- sub("\\..*$", "", tree$tip.label)

# Plot the tree
p1 <- ggtree(tree, layout="circular", size=.75, aes(color=as.numeric(label)), branch.length="none") +
  scale_color_gradient("Bootstrap", low = "green", high = "black", limits=c(0,100)) + 
  new_scale_color() +
  geom_tiplab(aes(color=ifelse(grepl("ASV", label), "blue", ifelse(grepl("culture", label), "red", "black"))), size=5) + 
  theme(
    legend.position = "bottom",
    legend.key.size = unit(4, "lines"),
    legend.text = element_text(size = 18),
    legend.title = element_text(size = 20)
  ) +
  scale_y_continuous(limits=c(1, 100)) +
  scale_color_identity() +
  labs(color = "Legend Title") # Add legend title

```

```{r}

# Save the plot to an image file
ggsave("NCBIreftree.svg", p1, width = 30, height = 26)
```
